# docker-compose.yml
version: '3'

services:
  django:
    build: .
    command: ["daphne", "sala_furiosa.asgi:application", "--bind", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=${redis_url}
      - DATABASE_URL=postgresql://${user}:${password}@${host}:6543/${dbname}

  redis:
    image: redis:alpine

