# docker-compose.yml
version: '3'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 sala_furiosa.asgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
