# Generated by Django 5.2 on 2025-04-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sala_furiosa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Mensagem',
        ),
    ]
